export const alertTypeStyle = {
  success: {
    borderRadius: 9,
    // opacity: 0.8,
    shadowColor: 'gray',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 1,
    margin: 12,
    backgroundColor: 'white',
    marginBottom: 40,
    borderLeftWidth: 5,
    borderLeftColor: 'green',
    height: 65,
  },
  error: {
    borderRadius: 9,
    // opacity: 0.8,
    shadowColor: 'gray',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 1,
    margin: 12,
    backgroundColor: 'white',
    marginBottom: 40,
    borderLeftWidth: 5,
    borderLeftColor: 'red',
    height: 65,
  },
};
